insert into inventory (name, quantity, price) values ('hydroxyzine hydrochloride', 146, 340321);
insert into inventory (name, quantity, price) values ('xtracare foaming facial cleanser', 122, 308104);
insert into inventory (name, quantity, price) values ('miconazole 7', 50, 178507);
insert into inventory (name, quantity, price) values ('voltaren', 103, 82189);
insert into inventory (name, quantity, price) values ('prednisone', 95, 249723);
insert into inventory (name, quantity, price) values ('perfect purity antibacterial gold', 100, 415236);
insert into inventory (name, quantity, price) values ('calamine', 89, 467912);
insert into inventory (name, quantity, price) values ('petrochemical detox', 120, 395581);
insert into inventory (name, quantity, price) values ('iodine bush', 130, 472831);
insert into inventory (name, quantity, price) values ('7 select allergy', 70, 368308);
insert into inventory (name, quantity, price) values ('rexall sleep aid', 84, 254480);
insert into inventory (name, quantity, price) values ('ponds', 83, 184393);
insert into inventory (name, quantity, price) values ('constipation', 96, 54044);
insert into inventory (name, quantity, price) values ('eszopiclone', 129, 279964);
insert into inventory (name, quantity, price) values ('flomax', 51, 205741);
insert into inventory (name, quantity, price) values ('pollens - trees, walnut, black juglans nigra', 103, 234912);
insert into inventory (name, quantity, price) values ('good sense childrens all day allergy', 105, 147934);
insert into inventory (name, quantity, price) values ('sunmark ibuprofen cold and sinus', 148, 282239);
insert into inventory (name, quantity, price) values ('max hyaluronic stemcell bb', 78, 181319);
insert into inventory (name, quantity, price) values ('digoxin', 84, 347211);
insert into inventory (name, quantity, price) values ('penicillin v potassium', 106, 468112);
insert into inventory (name, quantity, price) values ('fruit smoothies', 125, 125939);
insert into inventory (name, quantity, price) values ('ciprofloxacin', 79, 392280);
insert into inventory (name, quantity, price) values ('ibuprofen', 138, 269508);
insert into inventory (name, quantity, price) values ('oxcarbazepine', 132, 227130);
insert into inventory (name, quantity, price) values ('lorazepam', 58, 212528);
insert into inventory (name, quantity, price) values ('personal care petroleum jelly skin protectant', 106, 238872);
insert into inventory (name, quantity, price) values ('zantac', 122, 352128);
insert into inventory (name, quantity, price) values ('cesium chloride', 59, 252822);
insert into inventory (name, quantity, price) values ('hog epithelium', 136, 423098);
insert into inventory (name, quantity, price) values ('allergy relief', 121, 76230);
insert into inventory (name, quantity, price) values ('good neighbor pharmacy ibuprofen', 119, 425605);
insert into inventory (name, quantity, price) values ('rhodotorula mucilaginosa', 82, 128392);
insert into inventory (name, quantity, price) values ('warfarin sodium', 101, 379228);
insert into inventory (name, quantity, price) values ('badger spf 30 aloe sunscreen', 61, 497984);
insert into inventory (name, quantity, price) values ('norvasc', 67, 209150);
insert into inventory (name, quantity, price) values ('lamictal', 116, 88523);
insert into inventory (name, quantity, price) values ('allernaze', 127, 216417);
insert into inventory (name, quantity, price) values ('cystadane', 137, 217909);
insert into inventory (name, quantity, price) values ('ibuprofen', 79, 274419);
insert into inventory (name, quantity, price) values ('no7 lift and luminate day sunscreen broad spectrum spf 15', 105, 263000);
insert into inventory (name, quantity, price) values ('leader allergy multi symptom', 101, 136508);
insert into inventory (name, quantity, price) values ('sodium sulfacetamide and sulfur', 114, 233617);
insert into inventory (name, quantity, price) values ('topiclear skin lightening', 90, 142845);
insert into inventory (name, quantity, price) values ('good neighbor pharmacy pain relief', 122, 449913);
insert into inventory (name, quantity, price) values ('hydrating instant hand sanitizer', 124, 409925);
insert into inventory (name, quantity, price) values ('flu and severe cold and cough', 135, 397024);
insert into inventory (name, quantity, price) values ('hectorol', 116, 375706);
insert into inventory (name, quantity, price) values ('ipratropium bromide', 124, 84196);
insert into inventory (name, quantity, price) values ('ionite apf', 69, 447038);
insert into inventory (name, quantity, price) values ('advicor', 132, 478619);
insert into inventory (name, quantity, price) values ('obao frescura intensa', 65, 324042);
insert into inventory (name, quantity, price) values ('jason nutrismile anticavity orange cinnamon mint', 127, 334634);
insert into inventory (name, quantity, price) values ('navi mate gold', 118, 295456);
insert into inventory (name, quantity, price) values ('pred mild', 86, 243068);
insert into inventory (name, quantity, price) values ('propranolol hydrochloride and hydrochlorothiazide', 137, 120323);
insert into inventory (name, quantity, price) values ('loxapine', 124, 283551);
insert into inventory (name, quantity, price) values ('metaxalone', 82, 338717);
insert into inventory (name, quantity, price) values ('mycobutin', 125, 394847);
insert into inventory (name, quantity, price) values ('nbe cherry', 110, 174439);
insert into inventory (name, quantity, price) values ('careone', 136, 60073);
insert into inventory (name, quantity, price) values ('hydrocodone bitartrate and acetaminophen', 109, 364147);
insert into inventory (name, quantity, price) values ('healthy accents stay awake', 78, 274086);
insert into inventory (name, quantity, price) values ('colgate', 81, 346112);
insert into inventory (name, quantity, price) values ('chrono repair solaire', 67, 215219);
insert into inventory (name, quantity, price) values ('paroxetine', 100, 108356);
insert into inventory (name, quantity, price) values ('dye-free childrens acetaminophen grape', 71, 320134);
insert into inventory (name, quantity, price) values ('bronze booster bb cream', 76, 450325);
insert into inventory (name, quantity, price) values ('clearasil', 74, 303576);
insert into inventory (name, quantity, price) values ('temazepam', 66, 410595);
insert into inventory (name, quantity, price) values ('methimazole', 54, 122718);
insert into inventory (name, quantity, price) values ('treatment set ts348404', 86, 222605);
insert into inventory (name, quantity, price) values ('head and shoulders', 77, 227261);
insert into inventory (name, quantity, price) values ('pantoprazole sodium', 122, 104452);
insert into inventory (name, quantity, price) values ('cvs hydrocortisone with aloe', 79, 235341);
insert into inventory (name, quantity, price) values ('alprazolam', 124, 134766);
insert into inventory (name, quantity, price) values ('hahnemann colds', 91, 299050);
insert into inventory (name, quantity, price) values ('dermaklear akne treatment with sulfur', 59, 345256);
insert into inventory (name, quantity, price) values ('cc cream complexion corrector dark broad spectrum spf 15', 80, 344917);
insert into inventory (name, quantity, price) values ('hydrocodone bitartrate and acetaminophen', 55, 295976);
insert into inventory (name, quantity, price) values ('dove', 127, 184470);
insert into inventory (name, quantity, price) values ('pioglitazone hydrochloride', 93, 469542);
insert into inventory (name, quantity, price) values ('bronchial cough', 90, 486479);
insert into inventory (name, quantity, price) values ('xanthium strumarium var canadense pollen', 138, 449191);
insert into inventory (name, quantity, price) values ('safeway care', 127, 154739);
insert into inventory (name, quantity, price) values ('cepacol sensations', 105, 316989);
insert into inventory (name, quantity, price) values ('qsr hand sanitizer', 106, 307198);
insert into inventory (name, quantity, price) values ('chamomilla belladonna adult size', 120, 384082);
insert into inventory (name, quantity, price) values ('tagamet', 66, 95716);
insert into inventory (name, quantity, price) values ('gelusil', 76, 350080);
insert into inventory (name, quantity, price) values ('metronidazole', 101, 286984);
insert into inventory (name, quantity, price) values ('childrens qpap', 67, 136063);
insert into inventory (name, quantity, price) values ('metoprolol succinate', 125, 471935);
insert into inventory (name, quantity, price) values ('prednisone', 78, 489001);
insert into inventory (name, quantity, price) values ('butalbital, acetaminophen, and caffeine', 116, 434888);
insert into inventory (name, quantity, price) values ('nettle', 85, 455792);
insert into inventory (name, quantity, price) values ('antibacterial foaming hand sanitizer', 132, 316985);
insert into inventory (name, quantity, price) values ('pandel', 50, 360740);
insert into inventory (name, quantity, price) values ('vital-d rx', 55, 325182);
insert into inventory (name, quantity, price) values ('lidocaine and prilocaine', 88, 220151);
insert into inventory (name, quantity, price) values ('oxygen', 127, 374064);
insert into inventory (name, quantity, price) values ('migranade', 102, 222435);
insert into inventory (name, quantity, price) values ('health care personnel handwash', 123, 283723);
insert into inventory (name, quantity, price) values ('todays health nasal relief original', 104, 315399);
insert into inventory (name, quantity, price) values ('carboplatin', 106, 191710);
insert into inventory (name, quantity, price) values ('barbie striped fluoride', 73, 374106);
insert into inventory (name, quantity, price) values ('amoxicillin', 143, 71490);
insert into inventory (name, quantity, price) values ('carbamazepine', 65, 358704);
insert into inventory (name, quantity, price) values ('nicotine polacrilex, original', 137, 408028);
insert into inventory (name, quantity, price) values ('metformin hydrochloride', 108, 434801);
insert into inventory (name, quantity, price) values ('multi-symptom cold and cough daytime nighttime', 64, 387195);
insert into inventory (name, quantity, price) values ('levothyroxine sodium', 121, 457319);
insert into inventory (name, quantity, price) values ('glonoinum kit refill', 126, 165105);
insert into inventory (name, quantity, price) values ('agaricus equisetum special order', 96, 496721);
insert into inventory (name, quantity, price) values ('enjuvia', 58, 143753);
insert into inventory (name, quantity, price) values ('daytrana', 119, 96611);
insert into inventory (name, quantity, price) values ('enalapril maleate', 58, 250188);
insert into inventory (name, quantity, price) values ('cvs cold hot medicated', 83, 79215);
insert into inventory (name, quantity, price) values ('foaming hand sanitizer', 67, 354856);
insert into inventory (name, quantity, price) values ('zemplar', 135, 381431);
insert into inventory (name, quantity, price) values ('oxyrub pain relief', 149, 293823);
insert into inventory (name, quantity, price) values ('potato', 125, 419487);
insert into inventory (name, quantity, price) values ('arthrotec', 117, 317145);
insert into inventory (name, quantity, price) values ('aquaphor lip repair and protect', 144, 457714);
insert into inventory (name, quantity, price) values ('ethambutol hydrochloride', 143, 241161);
insert into inventory (name, quantity, price) values ('butalbital, aspirin, and caffeine', 88, 287006);
insert into inventory (name, quantity, price) values ('bupropion hydrochloride', 96, 282654);
insert into inventory (name, quantity, price) values ('4 kids complete cold and flu', 50, 332219);
insert into inventory (name, quantity, price) values ('lotronex', 129, 103390);
insert into inventory (name, quantity, price) values ('aspirin', 52, 273925);
insert into inventory (name, quantity, price) values ('acnefree', 82, 441517);
insert into inventory (name, quantity, price) values ('clindamycin hydrochloride', 71, 109377);
insert into inventory (name, quantity, price) values ('capture totale radiance restoring serum foundation spf 15 023', 90, 416355);
insert into inventory (name, quantity, price) values ('diclofenac sodium', 123, 71662);
insert into inventory (name, quantity, price) values ('california juniper pollen', 66, 409624);
insert into inventory (name, quantity, price) values ('suave', 131, 370919);
insert into inventory (name, quantity, price) values ('lotensin', 58, 177311);
insert into inventory (name, quantity, price) values ('oxycodone and acetaminophen', 50, 257846);
insert into inventory (name, quantity, price) values ('metoprolol tartrate', 74, 464872);
insert into inventory (name, quantity, price) values ('imiquimod', 106, 377846);
insert into inventory (name, quantity, price) values ('fluoxetine hydrochloride', 142, 115207);
insert into inventory (name, quantity, price) values ('candida albicans', 128, 121417);
insert into inventory (name, quantity, price) values ('bald cypress', 139, 466816);
insert into inventory (name, quantity, price) values ('antiseptic', 115, 335495);
insert into inventory (name, quantity, price) values ('topiramate', 83, 174487);
insert into inventory (name, quantity, price) values ('trazodone hydrochloride', 122, 90600);
insert into inventory (name, quantity, price) values ('glyburide', 89, 387293);
insert into inventory (name, quantity, price) values ('doxycycline hyclate', 72, 473289);
insert into inventory (name, quantity, price) values ('carbamazepine', 99, 273357);
insert into inventory (name, quantity, price) values ('quetiapine fumarate', 87, 478886);
insert into inventory (name, quantity, price) values ('yf-vax', 143, 407071);
insert into inventory (name, quantity, price) values ('napoleon perdis foundation stick broad spectrum spf 15 look 2', 80, 243175);
insert into inventory (name, quantity, price) values ('valacyclovir hydrochloride', 101, 120019);
insert into inventory (name, quantity, price) values ('menstrual - pms', 64, 126174);
insert into inventory (name, quantity, price) values ('hemorrhoid cream', 135, 451231);
insert into inventory (name, quantity, price) values ('ampicillin and sulbactam', 140, 184506);
insert into inventory (name, quantity, price) values ('food - dairy products, casein, cow milk', 99, 259035);
insert into inventory (name, quantity, price) values ('calming diaper rash', 114, 287892);
insert into inventory (name, quantity, price) values ('pumpkin spice antibacterial foaming hand wash', 92, 167220);
insert into inventory (name, quantity, price) values ('treatment set ts345784', 70, 331849);
insert into inventory (name, quantity, price) values ('zazole', 57, 359317);
insert into inventory (name, quantity, price) values ('ondansetron', 141, 482569);
insert into inventory (name, quantity, price) values ('ultravate', 77, 126600);
insert into inventory (name, quantity, price) values ('omidria', 140, 486438);
insert into inventory (name, quantity, price) values ('atomy mineral pact', 93, 178452);
insert into inventory (name, quantity, price) values ('fosinopril sodium and hydrochlorothiazide', 142, 279199);
insert into inventory (name, quantity, price) values ('diltiazem hydrochloride', 62, 98428);
insert into inventory (name, quantity, price) values ('mbm 13 female', 72, 296584);
insert into inventory (name, quantity, price) values ('mirtazapine', 118, 318422);
insert into inventory (name, quantity, price) values ('good sense nicotine', 112, 69498);
insert into inventory (name, quantity, price) values ('degree', 146, 78418);
insert into inventory (name, quantity, price) values ('plantago lanceolata pollen', 53, 52789);
insert into inventory (name, quantity, price) values ('subsys', 79, 498823);
insert into inventory (name, quantity, price) values ('nascobal', 130, 450960);
insert into inventory (name, quantity, price) values ('venlafaxine', 127, 398826);
insert into inventory (name, quantity, price) values ('colocynthis kit refill', 150, 322980);
insert into inventory (name, quantity, price) values ('simvastatin', 58, 344406);
insert into inventory (name, quantity, price) values ('nystatin', 91, 188430);
insert into inventory (name, quantity, price) values ('cobroxin', 96, 109189);
insert into inventory (name, quantity, price) values ('italian rye grass', 99, 88411);
insert into inventory (name, quantity, price) values ('center-al - quercus agrifolia pollen', 115, 189614);
insert into inventory (name, quantity, price) values ('ibuprofen', 54, 88219);
insert into inventory (name, quantity, price) values ('roxicet', 59, 116414);
insert into inventory (name, quantity, price) values ('plagentra baby', 111, 402332);
insert into inventory (name, quantity, price) values ('little remedies little tummys laxative drops', 135, 174036);
insert into inventory (name, quantity, price) values ('clarins ever matte broad spectrum spf 15 tint 114', 137, 281002);
insert into inventory (name, quantity, price) values ('relenza', 85, 100985);
insert into inventory (name, quantity, price) values ('phoma glomerata', 102, 207082);
insert into inventory (name, quantity, price) values ('minoxidil', 95, 221835);
insert into inventory (name, quantity, price) values ('risperidone', 127, 391253);
insert into inventory (name, quantity, price) values ('family care tolnaftate', 100, 355859);
insert into inventory (name, quantity, price) values ('methocarbamol', 106, 119476);
insert into inventory (name, quantity, price) values ('simply right nicotine', 145, 168414);
insert into inventory (name, quantity, price) values ('food - fish and shellfish, lobster homarus americanus', 148, 456632);
insert into inventory (name, quantity, price) values ('gesticare dha', 54, 388995);
insert into inventory (name, quantity, price) values ('fluocinonide', 76, 102845);
insert into inventory (name, quantity, price) values ('ipratropium bromide', 139, 185389);
insert into inventory (name, quantity, price) values ('adult tussin cough and cold cf', 93, 405916);
insert into inventory (name, quantity, price) values ('diphenhydramine hydrochloride', 66, 308660);
insert into inventory (name, quantity, price) values ('lbel maximum comfort and long-lasting foundation spf 10', 74, 187647);
insert into inventory (name, quantity, price) values ('hydrochlorothiazide', 115, 425391);
insert into inventory (name, quantity, price) values ('tacrolimus', 70, 264965);
insert into inventory (name, quantity, price) values ('naproxen', 55, 465616);
insert into inventory (name, quantity, price) values ('povidine iodine', 69, 119014);
insert into inventory (name, quantity, price) values ('j-max', 128, 312942);
insert into inventory (name, quantity, price) values ('anastrozole', 100, 290284);
insert into inventory (name, quantity, price) values ('furosemide', 99, 260164);
insert into inventory (name, quantity, price) values ('rexall nicotine', 79, 399309);
insert into inventory (name, quantity, price) values ('minocycline hydrochloride', 103, 156021);
insert into inventory (name, quantity, price) values ('loratadine', 90, 152351);
insert into inventory (name, quantity, price) values ('longleaf pine', 67, 168578);
insert into inventory (name, quantity, price) values ('pain relief pm', 100, 165861);
insert into inventory (name, quantity, price) values ('gabapentin', 56, 311278);
insert into inventory (name, quantity, price) values ('bzk towelette', 148, 59324);
insert into inventory (name, quantity, price) values ('all day allergy relief', 136, 324270);
insert into inventory (name, quantity, price) values ('antibacterial', 145, 322570);
insert into inventory (name, quantity, price) values ('ibuprofen', 136, 255693);
insert into inventory (name, quantity, price) values ('metronidazole', 88, 391561);
insert into inventory (name, quantity, price) values ('activella', 129, 201246);
insert into inventory (name, quantity, price) values ('lobster', 89, 318061);
insert into inventory (name, quantity, price) values ('pravastatin', 140, 84678);
insert into inventory (name, quantity, price) values ('center-al - poa pratensis pollen', 106, 109420);
insert into inventory (name, quantity, price) values ('sumatriptan succinate', 86, 56767);
insert into inventory (name, quantity, price) values ('citalopram', 92, 132697);
insert into inventory (name, quantity, price) values ('doxorubicin hydrochloride', 75, 280011);
insert into inventory (name, quantity, price) values ('phenytoin sodium', 51, 476350);
insert into inventory (name, quantity, price) values ('fluticasone propionate', 147, 346033);
insert into inventory (name, quantity, price) values ('phenytoin sodium', 140, 451932);
insert into inventory (name, quantity, price) values ('tizanidine hydrochloride', 103, 341078);
insert into inventory (name, quantity, price) values ('cetirizine hydrochloride', 52, 357927);
insert into inventory (name, quantity, price) values ('veal', 116, 424493);
insert into inventory (name, quantity, price) values ('collagen hd foundation', 123, 308533);
insert into inventory (name, quantity, price) values ('clarins broad spectrum spf 30 sunscreen for sun-sensitive areas', 130, 222743);
insert into inventory (name, quantity, price) values ('poppyseed', 138, 77891);
insert into inventory (name, quantity, price) values ('nifedipine', 135, 408372);
insert into inventory (name, quantity, price) values ('flurazepam', 118, 234548);
insert into inventory (name, quantity, price) values ('phenylephrine hydrochloride', 134, 354704);
insert into inventory (name, quantity, price) values ('cisatracurium besylate', 55, 433730);
insert into inventory (name, quantity, price) values ('indomethacin', 67, 189030);
insert into inventory (name, quantity, price) values ('metformin hydrochloride', 126, 282551);
insert into inventory (name, quantity, price) values ('piroxicam', 139, 462156);
insert into inventory (name, quantity, price) values ('formucare naproxen sodium', 81, 308949);
insert into inventory (name, quantity, price) values ('epirubicin hydrochloride', 107, 433389);
insert into inventory (name, quantity, price) values ('nisoldipine', 54, 125663);
insert into inventory (name, quantity, price) values ('ultimate daily face wash', 66, 231115);
insert into inventory (name, quantity, price) values ('oxygen', 53, 482468);
insert into inventory (name, quantity, price) values ('prograf', 58, 353283);
insert into inventory (name, quantity, price) values ('lisinopril', 80, 489551);
insert into inventory (name, quantity, price) values ('babies r us infants pain relief', 118, 56688);
insert into inventory (name, quantity, price) values ('i-max lightening l', 78, 381407);
insert into inventory (name, quantity, price) values ('sheep sorrel', 142, 100764);
insert into inventory (name, quantity, price) values ('vacuant', 129, 318875);
insert into inventory (name, quantity, price) values ('opana', 116, 355587);
insert into inventory (name, quantity, price) values ('gastropanpar', 90, 195536);
insert into inventory (name, quantity, price) values ('duetact', 112, 198194);
insert into inventory (name, quantity, price) values ('carbidopa, levodopa and entacapone', 117, 144686);
insert into inventory (name, quantity, price) values ('hyvee', 110, 57735);
insert into inventory (name, quantity, price) values ('benazepril hydrochloride', 98, 51093);
insert into inventory (name, quantity, price) values ('standardized grass pollen, sweet vernal grass', 75, 112532);
insert into inventory (name, quantity, price) values ('clarins hydraquench spf 15', 63, 486349);
insert into inventory (name, quantity, price) values ('select brand hemorrhoid', 126, 131755);
insert into inventory (name, quantity, price) values ('amoxicillin', 59, 105499);
insert into inventory (name, quantity, price) values ('cd diorskin star studio makeup spectacular brightening with sunscreen broad spectrum spf30 032', 112, 387431);
insert into inventory (name, quantity, price) values ('bp wash acne treatment pack', 122, 190843);
insert into inventory (name, quantity, price) values ('clearasil perfectawash', 62, 446156);
insert into inventory (name, quantity, price) values ('nitrogen', 116, 215710);
insert into inventory (name, quantity, price) values ('medi-first plus antacid', 107, 80292);
insert into inventory (name, quantity, price) values ('treatment set ts332340', 105, 142941);
insert into inventory (name, quantity, price) values ('pro-den rx', 103, 83715);
insert into inventory (name, quantity, price) values ('colocynthis kit refill', 78, 455398);
insert into inventory (name, quantity, price) values ('care one lice killing', 62, 58147);
insert into inventory (name, quantity, price) values ('gleostine', 55, 197781);
insert into inventory (name, quantity, price) values ('cisplatin', 108, 167663);
insert into inventory (name, quantity, price) values ('clobetasol propionate', 87, 376528);
insert into inventory (name, quantity, price) values ('atomy mineral pact', 104, 202536);
insert into inventory (name, quantity, price) values ('penicillin v potassium', 137, 58706);
insert into inventory (name, quantity, price) values ('tabcin', 94, 431686);
insert into inventory (name, quantity, price) values ('ondansetron hydrochloride', 105, 204072);
insert into inventory (name, quantity, price) values ('house dust', 138, 317038);
insert into inventory (name, quantity, price) values ('venlafaxine hydrochloride', 149, 407882);
insert into inventory (name, quantity, price) values ('diazepam', 112, 264035);
insert into inventory (name, quantity, price) values ('hives', 102, 133909);
insert into inventory (name, quantity, price) values ('pegasys', 122, 346288);
insert into inventory (name, quantity, price) values ('assure antiseptic hand wipes', 130, 146179);
insert into inventory (name, quantity, price) values ('antibacterial spray', 50, 173476);
insert into inventory (name, quantity, price) values ('hem-easy relief herbal anti-itch maximum itch relief', 87, 454445);
insert into inventory (name, quantity, price) values ('bareminerals prime time bb primer daily defense broad spectrum spf 30', 89, 226471);
insert into inventory (name, quantity, price) values ('anticavity fluoride rinse', 146, 356000);
insert into inventory (name, quantity, price) values ('pollens - trees, acacia acacia longifolia', 142, 474211);
insert into inventory (name, quantity, price) values ('humulin n', 107, 140168);
insert into inventory (name, quantity, price) values ('retaine mgd', 127, 346619);
insert into inventory (name, quantity, price) values ('carvedilol', 52, 470421);
insert into inventory (name, quantity, price) values ('natural fiber therapy natural laxative', 95, 221529);
insert into inventory (name, quantity, price) values ('purminerals 4 in 1 makeup spf 15 light', 53, 473460);
insert into inventory (name, quantity, price) values ('day relief night relief sinus pe', 67, 470777);
insert into inventory (name, quantity, price) values ('sinusalia', 90, 170348);
insert into inventory (name, quantity, price) values ('furosemide', 127, 253973);
insert into inventory (name, quantity, price) values ('pravastatin sodium', 121, 410462);
insert into inventory (name, quantity, price) values ('acyclovir', 99, 234771);
insert into inventory (name, quantity, price) values ('flounder', 99, 397660);
insert into inventory (name, quantity, price) values ('cuprum 5', 100, 318957);
insert into inventory (name, quantity, price) values ('topiramate', 134, 474175);
insert into inventory (name, quantity, price) values ('donepezil hydrochloride', 121, 199724);
insert into inventory (name, quantity, price) values ('head and shoulders 2in1', 119, 149313);
insert into inventory (name, quantity, price) values ('valacyclovir hydrochloride', 90, 281909);
insert into inventory (name, quantity, price) values ('ipratropium bromide', 93, 296692);
insert into inventory (name, quantity, price) values ('cold sore treatment', 57, 350455);
insert into inventory (name, quantity, price) values ('ampicillin', 70, 74304);
insert into inventory (name, quantity, price) values ('tizanidine hydrochloride', 85, 173722);
insert into inventory (name, quantity, price) values ('clear eyes travelers eye relief', 140, 136645);
insert into inventory (name, quantity, price) values ('benazepril hydrochloride', 127, 86837);
insert into inventory (name, quantity, price) values ('intervene makeup spf 15 soft porcelain', 139, 226812);
insert into inventory (name, quantity, price) values ('sore throat spray cherry', 84, 176119);
insert into inventory (name, quantity, price) values ('hot spot', 125, 346972);
insert into inventory (name, quantity, price) values ('berkley and jensen nicotine', 97, 292255);
insert into inventory (name, quantity, price) values ('clarithromycin', 81, 444331);
insert into inventory (name, quantity, price) values ('benazepril hydrochloride and hydrochlorothiazide', 149, 440865);
insert into inventory (name, quantity, price) values ('lansoprazole', 102, 61366);
insert into inventory (name, quantity, price) values ('sodium chloride', 52, 66923);
insert into inventory (name, quantity, price) values ('mirtazapine', 120, 455464);
insert into inventory (name, quantity, price) values ('etodolac', 146, 403354);
insert into inventory (name, quantity, price) values ('r.e.m. day spf 30', 113, 65767);
insert into inventory (name, quantity, price) values ('childrens pain relief grape', 129, 202111);
insert into inventory (name, quantity, price) values ('levetiracetam', 101, 116209);
insert into inventory (name, quantity, price) values ('keflex', 142, 226615);
insert into inventory (name, quantity, price) values ('tamsulosin hydrochloride', 111, 145395);
insert into inventory (name, quantity, price) values ('zidovudine', 67, 468094);
insert into inventory (name, quantity, price) values ('nitrogen', 82, 290801);
insert into inventory (name, quantity, price) values ('loblolly pine', 145, 421881);
insert into inventory (name, quantity, price) values ('oxacillin', 149, 480887);
insert into inventory (name, quantity, price) values ('zicam', 95, 77519);
insert into inventory (name, quantity, price) values ('meclizine hydrochloride', 72, 137846);
insert into inventory (name, quantity, price) values ('pain reliever pm', 90, 241671);
insert into inventory (name, quantity, price) values ('thiothixene', 56, 232538);
insert into inventory (name, quantity, price) values ('antimicrobial soap', 74, 150000);
insert into inventory (name, quantity, price) values ('gold bond baby cornstarch plus', 68, 421944);
insert into inventory (name, quantity, price) values ('ondansetron', 96, 443596);
insert into inventory (name, quantity, price) values ('dexamethasone sodium phosphate', 59, 419827);
insert into inventory (name, quantity, price) values ('metronidazole', 110, 241197);
insert into inventory (name, quantity, price) values ('sulfur 6', 138, 92617);
insert into inventory (name, quantity, price) values ('bismatrol', 116, 496482);
insert into inventory (name, quantity, price) values ('phendimetrazine tartrate', 130, 132465);
insert into inventory (name, quantity, price) values ('bystolic', 120, 413703);
insert into inventory (name, quantity, price) values ('ziks arthritis pain relief', 74, 401662);
insert into inventory (name, quantity, price) values ('dg health cold multi symptom', 146, 75770);
insert into inventory (name, quantity, price) values ('crestor', 105, 264661);
insert into inventory (name, quantity, price) values ('doxepin hydrochloride', 71, 237070);
insert into inventory (name, quantity, price) values ('androbalance', 52, 452647);
insert into inventory (name, quantity, price) values ('extra strength pain reliever', 144, 475844);
insert into inventory (name, quantity, price) values ('eo hand sanitizer', 88, 334652);
insert into inventory (name, quantity, price) values ('amlodipine besylate', 62, 471234);
insert into inventory (name, quantity, price) values ('shiseido advanced hydro-liquid compact (refill)', 107, 494337);
insert into inventory (name, quantity, price) values ('healthy accents cetirizine-d', 103, 151651);
insert into inventory (name, quantity, price) values ('coreg', 119, 388464);
insert into inventory (name, quantity, price) values ('bromocriptine mesylate', 75, 63156);
insert into inventory (name, quantity, price) values ('dry idea a.dry antiperspirant unscented', 56, 437522);
insert into inventory (name, quantity, price) values ('laxative', 89, 329814);
insert into inventory (name, quantity, price) values ('amlodipine besylate', 73, 459159);
insert into inventory (name, quantity, price) values ('metformin hydrochloride', 57, 282943);
insert into inventory (name, quantity, price) values ('stemphylium sarciniforms', 129, 166605);
insert into inventory (name, quantity, price) values ('pneumo hp', 88, 244690);
insert into inventory (name, quantity, price) values ('intelence', 96, 430817);
insert into inventory (name, quantity, price) values ('good sense sinus and allergy pe', 103, 435706);
insert into inventory (name, quantity, price) values ('dry idea advanced dry-cotton dry', 145, 369694);
insert into inventory (name, quantity, price) values ('duck meat', 91, 430363);
insert into inventory (name, quantity, price) values ('ampicillin and sulbactam', 128, 498666);
insert into inventory (name, quantity, price) values ('metformin hydrochloride', 78, 389947);
insert into inventory (name, quantity, price) values ('bayer migraine formula', 143, 488678);
insert into inventory (name, quantity, price) values ('cialis', 119, 228575);
insert into inventory (name, quantity, price) values ('xpect first aid buffered eye and skin', 75, 162444);
insert into inventory (name, quantity, price) values ('mediplast', 110, 197168);
insert into inventory (name, quantity, price) values ('meijer elements maximum strength for diaper rash', 103, 183300);
insert into inventory (name, quantity, price) values ('lisinopril and hydrochlorothiazide', 70, 278143);
insert into inventory (name, quantity, price) values ('dg health cold and flu relief', 105, 200381);
insert into inventory (name, quantity, price) values ('sarafem', 73, 369956);
insert into inventory (name, quantity, price) values ('warfarin sodium', 139, 342581);
insert into inventory (name, quantity, price) values ('clindamycin hydrochloride', 107, 415702);
insert into inventory (name, quantity, price) values ('coppertone kids sunscreen', 118, 313126);
insert into inventory (name, quantity, price) values ('estradiol', 142, 250510);
insert into inventory (name, quantity, price) values ('treatment set ts329467', 137, 359779);
insert into inventory (name, quantity, price) values ('iferex 150 forte', 140, 95181);
insert into inventory (name, quantity, price) values ('neutrogena', 123, 333689);
insert into inventory (name, quantity, price) values ('adrenalin', 99, 341917);
insert into inventory (name, quantity, price) values ('desmopressin acetate', 129, 452767);
insert into inventory (name, quantity, price) values ('glipizide', 96, 52926);
insert into inventory (name, quantity, price) values ('doxycycline hyclate', 92, 379565);
insert into inventory (name, quantity, price) values ('etodolac', 79, 280661);
insert into inventory (name, quantity, price) values ('stila illuminating tinted moisturizer broad spectrum spf 20', 85, 442457);
insert into inventory (name, quantity, price) values ('australian gold', 92, 390385);
insert into inventory (name, quantity, price) values ('warm sap patch', 109, 63994);
insert into inventory (name, quantity, price) values ('aspirin', 124, 127584);
insert into inventory (name, quantity, price) values ('zonatuss', 87, 202689);
insert into inventory (name, quantity, price) values ('trusopt', 141, 260241);
insert into inventory (name, quantity, price) values ('xylocaine', 62, 102461);
insert into inventory (name, quantity, price) values ('amlodipine besylate and benazepril hydrochloride', 89, 370115);
insert into inventory (name, quantity, price) values ('face saver gel', 93, 306376);
insert into inventory (name, quantity, price) values ('swim-ear', 145, 89516);
insert into inventory (name, quantity, price) values ('degree', 110, 337117);
insert into inventory (name, quantity, price) values ('dok', 112, 249169);
insert into inventory (name, quantity, price) values ('07 balancing foundation', 149, 347670);
insert into inventory (name, quantity, price) values ('aminocaproic acid', 63, 144175);
insert into inventory (name, quantity, price) values ('fungus free', 79, 408556);
insert into inventory (name, quantity, price) values ('doxercalciferol', 52, 391115);
insert into inventory (name, quantity, price) values ('carvedilol', 102, 53787);
insert into inventory (name, quantity, price) values ('foaming hand wash', 136, 91879);
insert into inventory (name, quantity, price) values ('clobetasol propionate', 100, 118315);
insert into inventory (name, quantity, price) values ('amoxicillin and clavulanate potassium', 102, 389650);
insert into inventory (name, quantity, price) values ('fentanyl', 136, 144952);
insert into inventory (name, quantity, price) values ('lamb quarters', 57, 477220);
insert into inventory (name, quantity, price) values ('ifosfamide', 100, 126092);
insert into inventory (name, quantity, price) values ('equate nicotine', 50, 93551);
insert into inventory (name, quantity, price) values ('verapamil hydrochloride', 131, 493679);
insert into inventory (name, quantity, price) values ('laura geller beauty tuscan sun spackle spf 30 protective under make-up primer porcelain', 117, 170605);
insert into inventory (name, quantity, price) values ('ximino', 85, 369857);
insert into inventory (name, quantity, price) values ('octreotide acetate', 73, 376107);
insert into inventory (name, quantity, price) values ('chloraprep one-step', 85, 291684);
insert into inventory (name, quantity, price) values ('atropine sulfate', 97, 352723);
insert into inventory (name, quantity, price) values ('chlorpromazine', 103, 249351);
insert into inventory (name, quantity, price) values ('ciprofloxacin', 54, 179483);
insert into inventory (name, quantity, price) values ('loratadine', 150, 168966);
insert into inventory (name, quantity, price) values ('indomethacin', 114, 99537);
insert into inventory (name, quantity, price) values ('sweet pea anti-bacterial scented hand sanitizer', 54, 200264);
insert into inventory (name, quantity, price) values ('humco camphor spirit', 130, 104387);
insert into inventory (name, quantity, price) values ('amoxicillin', 124, 333593);
insert into inventory (name, quantity, price) values ('the flower uv intense pact', 84, 473419);
insert into inventory (name, quantity, price) values ('fig', 99, 77860);
insert into inventory (name, quantity, price) values ('flurbiprofen', 98, 315240);
insert into inventory (name, quantity, price) values ('stavzor', 127, 157802);
insert into inventory (name, quantity, price) values ('arrid extra extra dry xx', 142, 392356);
insert into inventory (name, quantity, price) values ('night relief free', 86, 485253);
insert into inventory (name, quantity, price) values ('clonazepam', 57, 149632);
insert into inventory (name, quantity, price) values ('sun moon star', 138, 493763);
insert into inventory (name, quantity, price) values ('quetiapine fumarate', 120, 455485);
insert into inventory (name, quantity, price) values ('olanzapine', 118, 411432);
insert into inventory (name, quantity, price) values ('curity povidone-iodine scrub', 103, 291961);
insert into inventory (name, quantity, price) values ('myung han mi in do foundation', 106, 184897);
insert into inventory (name, quantity, price) values ('paroxetine', 53, 96055);
insert into inventory (name, quantity, price) values ('bisolvine', 76, 163198);
insert into inventory (name, quantity, price) values ('itchy skin runny nose', 131, 466781);
insert into inventory (name, quantity, price) values ('ibuprofen', 55, 95260);
insert into inventory (name, quantity, price) values ('valtrex', 110, 76463);
insert into inventory (name, quantity, price) values ('stannum 0.4', 69, 355659);
insert into inventory (name, quantity, price) values ('sorbet apf', 51, 214576);
insert into inventory (name, quantity, price) values ('sulfasalazine', 56, 275085);
insert into inventory (name, quantity, price) values ('bupropion hydrochloride', 93, 319475);
insert into inventory (name, quantity, price) values ('ampicillin and sulbactam', 87, 248574);
insert into inventory (name, quantity, price) values ('pantoprazole sodium', 110, 171459);
insert into inventory (name, quantity, price) values ('oxygen', 106, 220594);
insert into inventory (name, quantity, price) values ('equaline milk of magnesia', 83, 77305);
insert into inventory (name, quantity, price) values ('up and up sinus congestion and pain', 78, 96448);
insert into inventory (name, quantity, price) values ('dermasarra', 69, 288183);
insert into inventory (name, quantity, price) values ('neomycin and polymyxin b sulfates', 85, 204095);
insert into inventory (name, quantity, price) values ('bacitracin', 89, 498472);
insert into inventory (name, quantity, price) values ('neutrogena', 114, 348276);
insert into inventory (name, quantity, price) values ('cd diorskin forever flawless perfection fusion wear makeup spf 25 - 050', 119, 188827);
insert into inventory (name, quantity, price) values ('b-nexa', 119, 86379);
insert into inventory (name, quantity, price) values ('tranexamic acid', 135, 450959);
insert into inventory (name, quantity, price) values ('banana boat', 133, 153375);
insert into inventory (name, quantity, price) values ('asparagus', 124, 192674);
insert into inventory (name, quantity, price) values ('danazol', 139, 468896);
insert into inventory (name, quantity, price) values ('skin klear acne relief', 56, 162137);
insert into inventory (name, quantity, price) values ('cimicifuga homaccord', 134, 477260);
insert into inventory (name, quantity, price) values ('black birch', 57, 297464);
insert into inventory (name, quantity, price) values ('quetiapine fumarate', 53, 184802);
insert into inventory (name, quantity, price) values ('treatment set ts344420', 132, 367738);
insert into inventory (name, quantity, price) values ('naaman', 63, 301558);
insert into inventory (name, quantity, price) values ('crestor', 143, 143678);
insert into inventory (name, quantity, price) values ('ciprofloxacin', 89, 132230);
insert into inventory (name, quantity, price) values ('colgate', 123, 393896);
insert into inventory (name, quantity, price) values ('balance-n-brighten', 57, 425466);
insert into inventory (name, quantity, price) values ('midazolam', 67, 343957);
insert into inventory (name, quantity, price) values ('active-pac with gabapentin', 130, 105672);
insert into inventory (name, quantity, price) values ('heparin sodium', 71, 473055);
insert into inventory (name, quantity, price) values ('levofloxacin', 58, 90908);
insert into inventory (name, quantity, price) values ('methocarbamol', 85, 350289);
insert into inventory (name, quantity, price) values ('amrix', 64, 341839);
insert into inventory (name, quantity, price) values ('standardized grass pollen, redtop', 92, 375591);
insert into inventory (name, quantity, price) values ('safeway sennosides', 83, 176903);
insert into inventory (name, quantity, price) values ('carbon dioxide-oxygen mixture', 108, 391477);
insert into inventory (name, quantity, price) values ('ropinirole hydrochloride', 95, 260047);
insert into inventory (name, quantity, price) values ('methyldopa', 123, 53987);
insert into inventory (name, quantity, price) values ('amaranthus spinosus pollen', 71, 298721);
insert into inventory (name, quantity, price) values ('st. joseph chewable aspirin', 56, 480541);
insert into inventory (name, quantity, price) values ('complete', 130, 460636);
insert into inventory (name, quantity, price) values ('penicillin v potassium', 124, 246934);
insert into inventory (name, quantity, price) values ('sleep aid', 96, 422944);
insert into inventory (name, quantity, price) values ('ultravist', 102, 447073);
insert into inventory (name, quantity, price) values ('furosemide', 83, 57882);
insert into inventory (name, quantity, price) values ('vogelxo', 138, 89903);
insert into inventory (name, quantity, price) values ('minocycline hydrochloride', 146, 326731);
insert into inventory (name, quantity, price) values ('tinnitus', 95, 66907);
insert into inventory (name, quantity, price) values ('nausea vomiting hp', 62, 215265);
insert into inventory (name, quantity, price) values ('lidocaine hydrochloride', 59, 191064);
insert into inventory (name, quantity, price) values ('zolpidem tartrate', 90, 99427);
insert into inventory (name, quantity, price) values ('care one', 65, 469182);
insert into inventory (name, quantity, price) values ('degree women ultraclear pure rain', 141, 227489);
insert into inventory (name, quantity, price) values ('sodium sulfacetamide 10 sulfur 2 cleanser', 143, 496010);
insert into inventory (name, quantity, price) values ('ibuprofen', 135, 141737);
insert into inventory (name, quantity, price) values ('good sense naproxen sodium', 112, 465304);
insert into inventory (name, quantity, price) values ('pain relief therapy patch', 80, 278842);
insert into inventory (name, quantity, price) values ('hand sanitizer', 80, 417070);
insert into inventory (name, quantity, price) values ('risperidone', 96, 487468);
insert into inventory (name, quantity, price) values ('ribasphere', 52, 197786);
insert into inventory (name, quantity, price) values ('caffeine', 81, 91687);
insert into inventory (name, quantity, price) values ('candida', 92, 198633);
insert into inventory (name, quantity, price) values ('acne medication 5', 139, 481380);
insert into inventory (name, quantity, price) values ('acetone isopropyl alcohol', 88, 323428);
insert into inventory (name, quantity, price) values ('sodium sulfacetamide, sulfur', 95, 110562);
insert into inventory (name, quantity, price) values ('virotox', 56, 362608);
insert into inventory (name, quantity, price) values ('aspirin', 86, 333303);
insert into inventory (name, quantity, price) values ('quality choice mucus relief dm', 76, 145921);
insert into inventory (name, quantity, price) values ('treatment set ts329162', 80, 181120);
insert into inventory (name, quantity, price) values ('humulin 70/30', 53, 311971);
insert into inventory (name, quantity, price) values ('paroxetine', 145, 402428);
insert into inventory (name, quantity, price) values ('promethazine hydrochloride', 132, 453552);
insert into inventory (name, quantity, price) values ('neurosode', 126, 135683);
insert into inventory (name, quantity, price) values ('carvedilol', 114, 261929);
insert into inventory (name, quantity, price) values ('ramipril', 93, 72874);
insert into inventory (name, quantity, price) values ('lbel couleur luxe rouge amplifier xp amplifying spf 15', 126, 212279);
insert into inventory (name, quantity, price) values ('tetracaine hydrochloride', 50, 413909);
insert into inventory (name, quantity, price) values ('losortan potassium', 124, 467409);
insert into inventory (name, quantity, price) values ('labetalol hydrochloride', 96, 234651);
insert into inventory (name, quantity, price) values ('lisinopril', 97, 473187);
insert into inventory (name, quantity, price) values ('arneu', 121, 109171);
insert into inventory (name, quantity, price) values ('albuked', 150, 116430);
insert into inventory (name, quantity, price) values ('foamfresh alco-foam hand sanitizer', 102, 408047);
insert into inventory (name, quantity, price) values ('paclitaxel', 107, 336355);
insert into inventory (name, quantity, price) values ('baclofen', 78, 137930);
insert into inventory (name, quantity, price) values ('anti-aging concealer face eyes sunscreen spf 20 shade 30', 95, 214319);
insert into inventory (name, quantity, price) values ('oxycodone hydrochloride', 61, 403161);
insert into inventory (name, quantity, price) values ('lettuce', 66, 248839);
insert into inventory (name, quantity, price) values ('zolpidem tartrate', 56, 83795);
insert into inventory (name, quantity, price) values ('repara', 121, 156702);
insert into inventory (name, quantity, price) values ('novolog mix 70/30', 68, 335355);
insert into inventory (name, quantity, price) values ('equate childrens pain and fever', 118, 486214);
insert into inventory (name, quantity, price) values ('garlic', 129, 61613);
insert into inventory (name, quantity, price) values ('leader sore throat', 69, 209454);
insert into inventory (name, quantity, price) values ('burkhart neutral', 105, 458162);
insert into inventory (name, quantity, price) values ('amlodipine besylate/atorvastatin calcium', 81, 108352);
insert into inventory (name, quantity, price) values ('oxymorphone hydrochloride', 86, 281912);
insert into inventory (name, quantity, price) values ('lipitor', 52, 364230);
insert into inventory (name, quantity, price) values ('saltbush', 121, 334741);
insert into inventory (name, quantity, price) values ('no7 beautifully matte foundation sunscreen broad spectrum spf 15 mocha', 62, 258732);
insert into inventory (name, quantity, price) values ('reguloid', 144, 379990);
insert into inventory (name, quantity, price) values ('zicam', 113, 324635);
insert into inventory (name, quantity, price) values ('bio-scriptives lidum', 142, 440629);
insert into inventory (name, quantity, price) values ('pollens - trees, olive olea europaea', 68, 250570);
insert into inventory (name, quantity, price) values ('letrozole', 95, 421795);
insert into inventory (name, quantity, price) values ('enteric coated aspirin', 121, 191266);
insert into inventory (name, quantity, price) values ('hydrocortisone', 90, 420374);
insert into inventory (name, quantity, price) values ('good neighbor pharmacy pain and fever', 148, 184019);
insert into inventory (name, quantity, price) values ('anti-bacterial hand', 124, 190671);
insert into inventory (name, quantity, price) values ('venlafaxine hydrochloride', 129, 350592);
insert into inventory (name, quantity, price) values ('genotropin', 69, 288495);
insert into inventory (name, quantity, price) values ('prednisolone', 72, 163337);
insert into inventory (name, quantity, price) values ('rifampin', 149, 361221);
insert into inventory (name, quantity, price) values ('nivea a kiss of strawberry fruity lip care', 100, 157706);
insert into inventory (name, quantity, price) values ('marcaine', 69, 413560);
insert into inventory (name, quantity, price) values ('leucovorin calcium', 120, 237974);
insert into inventory (name, quantity, price) values ('tuscan lemon antibacterial foaming hand wash', 60, 425627);
insert into inventory (name, quantity, price) values ('zicam ultra cold remedy rapidmelts', 90, 358862);
insert into inventory (name, quantity, price) values ('terazosin hydrochloride', 121, 75457);
insert into inventory (name, quantity, price) values ('promethazine vc', 101, 362386);
insert into inventory (name, quantity, price) values ('synthroid', 145, 419289);
insert into inventory (name, quantity, price) values ('artery/cholesterol/bp', 61, 446215);
insert into inventory (name, quantity, price) values ('morphine sulfate', 78, 379545);
insert into inventory (name, quantity, price) values ('amoxicillin and clavulanate potassium', 83, 406242);
insert into inventory (name, quantity, price) values ('vecuronium bromide', 138, 262863);
insert into inventory (name, quantity, price) values ('instant hand sanitizer', 124, 200403);
insert into inventory (name, quantity, price) values ('dalan golden tropics antibacterial deodorant', 99, 416734);
insert into inventory (name, quantity, price) values ('oxycontin', 99, 82984);
insert into inventory (name, quantity, price) values ('lady speed stick', 142, 353528);
insert into inventory (name, quantity, price) values ('invirase', 125, 450460);
insert into inventory (name, quantity, price) values ('diabecline', 98, 170068);
insert into inventory (name, quantity, price) values ('mastic dent oulo action', 66, 90920);
insert into inventory (name, quantity, price) values ('clomiphene citrate', 149, 456882);
insert into inventory (name, quantity, price) values ('leader childrens pain and fever', 125, 81625);
insert into inventory (name, quantity, price) values ('vanilla hand sanitizer', 92, 498931);
insert into inventory (name, quantity, price) values ('clarithromycin', 100, 327368);
insert into inventory (name, quantity, price) values ('treatment set ts349290', 106, 478751);
insert into inventory (name, quantity, price) values ('cardinalhealth alcohol prep pads large', 123, 145031);
insert into inventory (name, quantity, price) values ('metal-chord', 97, 97332);
insert into inventory (name, quantity, price) values ('megestrol acetate', 78, 473064);
insert into inventory (name, quantity, price) values ('orchard grass, standardized', 106, 194404);
insert into inventory (name, quantity, price) values ('profen ib', 84, 319168);
insert into inventory (name, quantity, price) values ('anthemis nobilis', 124, 153857);
insert into inventory (name, quantity, price) values ('socalm', 86, 365353);
insert into inventory (name, quantity, price) values ('doxycycline hyclate', 117, 234982);
insert into inventory (name, quantity, price) values ('dr. cocoa nighttime cough and cold', 51, 373977);
insert into inventory (name, quantity, price) values ('leucovorin calcium', 93, 455086);
insert into inventory (name, quantity, price) values ('dextroamphetamine saccharate, amphetamine aspartate, dextroamphetamine sulfate, and amphetamine sulfate', 111, 256809);
insert into inventory (name, quantity, price) values ('restfully sleep', 145, 409952);
insert into inventory (name, quantity, price) values ('oxymorphone hydrochloride', 130, 299443);
insert into inventory (name, quantity, price) values ('joint and muscle pain', 130, 158312);
insert into inventory (name, quantity, price) values ('sun shades', 67, 216787);
insert into inventory (name, quantity, price) values ('meclizine hydrochloride', 105, 498894);
insert into inventory (name, quantity, price) values ('diclofenac sodium', 71, 112715);
insert into inventory (name, quantity, price) values ('birds garden lip balm', 53, 260147);
insert into inventory (name, quantity, price) values ('ramipril', 56, 281443);
insert into inventory (name, quantity, price) values ('hawaiian tropic', 122, 228275);
insert into inventory (name, quantity, price) values ('prednisone', 81, 126975);
insert into inventory (name, quantity, price) values ('carvedilol', 60, 470675);
insert into inventory (name, quantity, price) values ('fluphenazine hydrochloride', 59, 313710);
insert into inventory (name, quantity, price) values ('adempas', 119, 278617);
insert into inventory (name, quantity, price) values ('heparin sodium', 87, 167669);
insert into inventory (name, quantity, price) values ('sotradecol', 116, 137228);
insert into inventory (name, quantity, price) values ('chap-et', 142, 271437);
insert into inventory (name, quantity, price) values ('septaforce', 88, 226533);
insert into inventory (name, quantity, price) values ('topcare fexofenadine hydrochloride', 92, 415346);
insert into inventory (name, quantity, price) values ('sodium fluoride', 133, 294479);
insert into inventory (name, quantity, price) values ('prevalite', 126, 461051);
insert into inventory (name, quantity, price) values ('metoprolol tartrate', 142, 337047);
insert into inventory (name, quantity, price) values ('lomotil', 109, 346082);
insert into inventory (name, quantity, price) values ('phenol', 52, 265846);
insert into inventory (name, quantity, price) values ('lice complete', 62, 167874);
insert into inventory (name, quantity, price) values ('amlodipine besylate and benazepril hydrochloride', 81, 447211);
insert into inventory (name, quantity, price) values ('molds, rusts and smuts, epicoccum nigrum', 137, 344515);
insert into inventory (name, quantity, price) values ('naproxen sodium', 67, 413661);
insert into inventory (name, quantity, price) values ('losartan potassium', 106, 335551);
insert into inventory (name, quantity, price) values ('3 concept eyes glossing waterful foundation milk ivory', 96, 466979);
insert into inventory (name, quantity, price) values ('good neighbor pharmacy day time', 94, 382263);
insert into inventory (name, quantity, price) values ('gemfibrozil', 120, 210435);
insert into inventory (name, quantity, price) values ('butalbital, acetaminophen and caffeine', 70, 177045);
insert into inventory (name, quantity, price) values ('eys eye wash', 74, 404311);
insert into inventory (name, quantity, price) values ('banana boat ultra defense', 91, 181873);
insert into inventory (name, quantity, price) values ('necon 1/35', 101, 437697);
insert into inventory (name, quantity, price) values ('traumeel', 61, 250819);
insert into inventory (name, quantity, price) values ('cold-eeze', 87, 347345);
insert into inventory (name, quantity, price) values ('lescol', 90, 64650);
insert into inventory (name, quantity, price) values ('montelukast sodium', 85, 235647);
insert into inventory (name, quantity, price) values ('whiskcare 367', 85, 130357);
insert into inventory (name, quantity, price) values ('cle de peau beaute radiant fluid foundation', 105, 256063);
insert into inventory (name, quantity, price) values ('recombivax hb', 83, 165841);
insert into inventory (name, quantity, price) values ('clopidogrel bisulfate', 96, 284791);
insert into inventory (name, quantity, price) values ('dr.g whitening booster ample', 56, 226920);
insert into inventory (name, quantity, price) values ('california live oak', 75, 159188);
insert into inventory (name, quantity, price) values ('meperidine hydrochloride', 130, 422940);
insert into inventory (name, quantity, price) values ('furosemide', 127, 263543);
insert into inventory (name, quantity, price) values ('cover tint', 120, 307532);
insert into inventory (name, quantity, price) values ('losartan potassium', 92, 64899);
insert into inventory (name, quantity, price) values ('methadone hydrochloride', 136, 68913);
insert into inventory (name, quantity, price) values ('childrens pain reliever', 125, 210126);
insert into inventory (name, quantity, price) values ('hemorrhoidal pad', 145, 372892);
insert into inventory (name, quantity, price) values ('neomycin polymyxin b sulfates and dexamethasone', 53, 127914);
insert into inventory (name, quantity, price) values ('zyloprim', 128, 266490);
insert into inventory (name, quantity, price) values ('pain relief', 140, 333744);
insert into inventory (name, quantity, price) values ('sodium hydroxide', 55, 156922);
insert into inventory (name, quantity, price) values ('colgate optic white', 133, 62882);
insert into inventory (name, quantity, price) values ('care one pain relief', 76, 242713);
insert into inventory (name, quantity, price) values ('quinapril hydrochloride/hydrochlorothiazide', 128, 81698);
insert into inventory (name, quantity, price) values ('givenchy teint couture long wearing fluid foundation with sunscreen broad spectrum spf 20 elegant beige', 108, 205706);
insert into inventory (name, quantity, price) values ('fibromyalgia', 76, 84139);
insert into inventory (name, quantity, price) values ('metaxalone', 79, 271210);
insert into inventory (name, quantity, price) values ('nigrospora sphaerica', 132, 181237);
insert into inventory (name, quantity, price) values ('pramipexole dihydrochloride', 72, 341348);
insert into inventory (name, quantity, price) values ('gabapentin', 68, 482829);
insert into inventory (name, quantity, price) values ('salicylic acid', 116, 413451);
insert into inventory (name, quantity, price) values ('oxycodone hydrochloride', 60, 189704);
insert into inventory (name, quantity, price) values ('cephalexin', 56, 107598);
insert into inventory (name, quantity, price) values ('medicated apricot scrub', 108, 325616);
insert into inventory (name, quantity, price) values ('wal-phed pe', 109, 306589);
insert into inventory (name, quantity, price) values ('doxepin hydrochloride', 57, 54749);
insert into inventory (name, quantity, price) values ('clotrimazole', 76, 56202);
insert into inventory (name, quantity, price) values ('gold bond intensive healing anti itch skin protectant', 150, 461136);
insert into inventory (name, quantity, price) values ('smart sense', 57, 372525);
insert into inventory (name, quantity, price) values ('perphenazine', 144, 254725);
insert into inventory (name, quantity, price) values ('phenazopyridine hydrochloride', 64, 257838);
insert into inventory (name, quantity, price) values ('h-psoriasis formula', 96, 149857);
insert into inventory (name, quantity, price) values ('tobacco leaf', 95, 302218);
insert into inventory (name, quantity, price) values ('colcrys', 84, 212463);
insert into inventory (name, quantity, price) values ('rite aid', 120, 446954);
insert into inventory (name, quantity, price) values ('warfarin sodium', 104, 206242);
insert into inventory (name, quantity, price) values ('head and shoulders conditioner', 50, 475997);
insert into inventory (name, quantity, price) values ('shiseido sheer matifying compact (refill)', 85, 83256);
insert into inventory (name, quantity, price) values ('voltaren', 97, 78585);
insert into inventory (name, quantity, price) values ('tagamet', 140, 383830);
insert into inventory (name, quantity, price) values ('oxygen', 139, 223356);
insert into inventory (name, quantity, price) values ('prandimet', 122, 302173);
insert into inventory (name, quantity, price) values ('glipizide', 141, 210620);
insert into inventory (name, quantity, price) values ('dynarex green', 87, 200386);
insert into inventory (name, quantity, price) values ('mk povidone-iodine swabstick sterile', 69, 56177);
insert into inventory (name, quantity, price) values ('childrens plus multi-symptom cold grape', 104, 332117);
insert into inventory (name, quantity, price) values ('swimmers support', 95, 415429);
insert into inventory (name, quantity, price) values ('ativan', 107, 455721);
insert into inventory (name, quantity, price) values ('felodipineextended-release tablets', 99, 204223);
insert into inventory (name, quantity, price) values ('isopropyl alcohol', 93, 97616);
insert into inventory (name, quantity, price) values ('rugby heartburn treatment', 106, 335141);
insert into inventory (name, quantity, price) values ('moisturizing antibacterial', 115, 297730);
insert into inventory (name, quantity, price) values ('skin so soft', 146, 320521);
insert into inventory (name, quantity, price) values ('carvedilol', 141, 139716);
insert into inventory (name, quantity, price) values ('meloxicam', 73, 323216);
insert into inventory (name, quantity, price) values ('false ragweed', 128, 225866);
insert into inventory (name, quantity, price) values ('lidocaine hydrochloride', 125, 435334);
insert into inventory (name, quantity, price) values ('carbon dioxide', 85, 53616);
insert into inventory (name, quantity, price) values ('sunmark nite time d', 55, 115675);
insert into inventory (name, quantity, price) values ('mycocan-chord', 129, 353454);
insert into inventory (name, quantity, price) values ('probee water soluble propolis', 115, 222458);
insert into inventory (name, quantity, price) values ('hepagam b', 51, 228152);
insert into inventory (name, quantity, price) values ('clonidine hydrochloride', 81, 146179);
insert into inventory (name, quantity, price) values ('rabbit epithelium', 110, 468209);
insert into inventory (name, quantity, price) values ('candesartan cilexetil', 147, 160968);
insert into inventory (name, quantity, price) values ('cold-eeze', 128, 276963);
insert into inventory (name, quantity, price) values ('iope retigen essence dual concealer', 94, 444045);
insert into inventory (name, quantity, price) values ('syagrus romanzoffiana pollen', 85, 412758);
insert into inventory (name, quantity, price) values ('amoxicillin', 102, 382966);
insert into inventory (name, quantity, price) values ('lemon verbena hand sanitizer', 125, 375291);
insert into inventory (name, quantity, price) values ('ocean potion instant dry 30 mist water sport sunscreen', 51, 101962);
insert into inventory (name, quantity, price) values ('lamotrigine', 109, 310329);
insert into inventory (name, quantity, price) values ('therapeutic plus', 68, 170143);
insert into inventory (name, quantity, price) values ('african formula skin lightening', 134, 259445);
insert into inventory (name, quantity, price) values ('allergy', 116, 125844);
insert into inventory (name, quantity, price) values ('aplicare total joint prep', 117, 90142);
insert into inventory (name, quantity, price) values ('royal antibacterial raspberry hand cleanse', 98, 274808);
insert into inventory (name, quantity, price) values ('sertraline', 62, 304677);
insert into inventory (name, quantity, price) values ('nosmotea', 88, 137203);
insert into inventory (name, quantity, price) values ('superman berry scented antiseptic hand cleansing', 51, 81826);
insert into inventory (name, quantity, price) values ('medroxyprogesterone acetate', 63, 226245);
insert into inventory (name, quantity, price) values ('smart sense severe cold and flu nighttime', 63, 424255);
insert into inventory (name, quantity, price) values ('clearasil daily clear', 72, 263133);
insert into inventory (name, quantity, price) values ('simvastatin', 136, 187607);
insert into inventory (name, quantity, price) values ('pms irritability', 77, 96880);
insert into inventory (name, quantity, price) values ('phisoderm clear confidence body wash', 70, 433450);
insert into inventory (name, quantity, price) values ('toppik womens hair regrowth treatment', 127, 491511);
insert into inventory (name, quantity, price) values ('butalbital, acetaminophen, caffeine', 139, 170446);
insert into inventory (name, quantity, price) values ('zaleplon', 104, 97199);
insert into inventory (name, quantity, price) values ('promethazine hydrochloride', 103, 445405);
insert into inventory (name, quantity, price) values ('metformin hydrochloride', 70, 150104);
insert into inventory (name, quantity, price) values ('kids sunscreen', 135, 70712);
insert into inventory (name, quantity, price) values ('stool softener', 128, 390113);
insert into inventory (name, quantity, price) values ('metformin hydrochloride', 131, 462373);
insert into inventory (name, quantity, price) values ('benazepril hydrochloride', 67, 330580);
insert into inventory (name, quantity, price) values ('ondansetron hydrochloride', 60, 91191);
insert into inventory (name, quantity, price) values ('equaline clotrimazole antifungal', 93, 328535);
insert into inventory (name, quantity, price) values ('riluzole', 139, 345879);
insert into inventory (name, quantity, price) values ('thai herbal balm lemon grass', 143, 426588);
insert into inventory (name, quantity, price) values ('black radiance true complexion bb cream spf 15', 53, 253076);
insert into inventory (name, quantity, price) values ('metaproterenol sulfate', 51, 157199);
insert into inventory (name, quantity, price) values ('la roche posay laboratoire dermatologique pigmentclar daily dark spot correcting moisturizer broad spectrum spf 30 sunscreen', 135, 389551);
insert into inventory (name, quantity, price) values ('rohto arctic', 83, 232254);
insert into inventory (name, quantity, price) values ('thalomid', 127, 465200);
insert into inventory (name, quantity, price) values ('lidocaine hcl - hydrocortisone acetate', 138, 331112);
insert into inventory (name, quantity, price) values ('buprenorphine hydrochloride', 123, 102539);
insert into inventory (name, quantity, price) values ('prazosin hydrochloride', 108, 327519);
insert into inventory (name, quantity, price) values ('cimetidine', 53, 494043);
insert into inventory (name, quantity, price) values ('maximum strength flu bp', 90, 303197);
insert into inventory (name, quantity, price) values ('the gargle', 95, 462749);
insert into inventory (name, quantity, price) values ('stage fright - fear', 93, 274390);
insert into inventory (name, quantity, price) values ('lyrica', 150, 235770);
insert into inventory (name, quantity, price) values ('anti-bacterial hand', 73, 198131);
insert into inventory (name, quantity, price) values ('arterioforce', 116, 493388);
insert into inventory (name, quantity, price) values ('trileptal', 122, 161071);
insert into inventory (name, quantity, price) values ('celebrex', 71, 483888);
insert into inventory (name, quantity, price) values ('meijer sport spf 50', 132, 320440);
insert into inventory (name, quantity, price) values ('plantago lanceolata pollen', 85, 388591);
insert into inventory (name, quantity, price) values ('sinus clear', 139, 421214);
insert into inventory (name, quantity, price) values ('prostatone', 86, 382855);
insert into inventory (name, quantity, price) values ('ck one all day perfection face makeup', 61, 434840);
insert into inventory (name, quantity, price) values ('ranitidine', 58, 402710);
insert into inventory (name, quantity, price) values ('clarins sunscreen for eyes wrinkle control spf 30 uva/uvb', 95, 149042);
insert into inventory (name, quantity, price) values ('zenpep', 143, 68516);
insert into inventory (name, quantity, price) values ('morphine sulfate', 71, 100236);
insert into inventory (name, quantity, price) values ('hydrochlorothiazide', 55, 447621);
insert into inventory (name, quantity, price) values ('oxybutynin chloride', 70, 433507);
insert into inventory (name, quantity, price) values ('center-al - quercus virginiana pollen', 135, 195791);
insert into inventory (name, quantity, price) values ('enoxaparin sodium', 124, 259493);
insert into inventory (name, quantity, price) values ('head and shoulders', 68, 383780);
insert into inventory (name, quantity, price) values ('fentanyl citrate', 60, 348913);
insert into inventory (name, quantity, price) values ('eau thermale avene moderate protection broad spectrum spf 20', 106, 140243);
insert into inventory (name, quantity, price) values ('leuprolide acetate', 103, 81911);
insert into inventory (name, quantity, price) values ('ohui age recovery tri shield pact 10', 115, 421018);
insert into inventory (name, quantity, price) values ('jeuncell hair restorer and hair growth solution', 90, 306721);
insert into inventory (name, quantity, price) values ('seroquel', 133, 261752);
insert into inventory (name, quantity, price) values ('topcare cold sore treatment', 97, 274281);
insert into inventory (name, quantity, price) values ('anticavity rinse', 55, 471195);
insert into inventory (name, quantity, price) values ('ganirelix acetate', 135, 498185);
insert into inventory (name, quantity, price) values ('mada medical', 116, 51414);
insert into inventory (name, quantity, price) values ('long lasting finish with comfort serum', 117, 218814);
insert into inventory (name, quantity, price) values ('body time anti-aging day cream spf 30', 105, 235459);
insert into inventory (name, quantity, price) values ('synthroid', 87, 117572);
insert into inventory (name, quantity, price) values ('zebutal', 56, 483031);
insert into inventory (name, quantity, price) values ('amitiza', 77, 292273);
insert into inventory (name, quantity, price) values ('house dust mite, dermatophagoides pteronyssinus', 112, 177881);
insert into inventory (name, quantity, price) values ('bupropion hydrochloride', 142, 263491);
insert into inventory (name, quantity, price) values ('blue ice analgesic gel', 137, 295667);
insert into inventory (name, quantity, price) values ('ligustrum vulgare pollen', 81, 178297);
insert into inventory (name, quantity, price) values ('finasteride', 112, 52864);
insert into inventory (name, quantity, price) values ('topcare cold', 110, 467689);
insert into inventory (name, quantity, price) values ('lip smacker spf cherry berry ball', 79, 69252);
insert into inventory (name, quantity, price) values ('pain relief ibuprofen', 101, 325756);
insert into inventory (name, quantity, price) values ('skintx daily defense', 136, 70942);
insert into inventory (name, quantity, price) values ('sorbet apf', 146, 96318);
insert into inventory (name, quantity, price) values ('meloxicam', 135, 74997);
insert into inventory (name, quantity, price) values ('aspirin', 91, 95659);
insert into inventory (name, quantity, price) values ('lbel efet parfait spots reducing effect foundation spf 18 - claire 4', 100, 64979);
insert into inventory (name, quantity, price) values ('ammonium lactate', 98, 393256);
insert into inventory (name, quantity, price) values ('oxygen', 56, 435121);
insert into inventory (name, quantity, price) values ('cladosporium sphaerospermum', 61, 484117);
insert into inventory (name, quantity, price) values ('smart sense', 79, 466376);
insert into inventory (name, quantity, price) values ('target cold/flu relief', 53, 465830);
insert into inventory (name, quantity, price) values ('promethazine hydrochloride', 122, 85606);
insert into inventory (name, quantity, price) values ('fatigue relief', 110, 429318);
insert into inventory (name, quantity, price) values ('clonazepam', 84, 107884);
insert into inventory (name, quantity, price) values ('amorepacific', 127, 78871);
insert into inventory (name, quantity, price) values ('ketorolac tromethamine', 95, 362949);
insert into inventory (name, quantity, price) values ('zicam', 114, 498977);
insert into inventory (name, quantity, price) values ('lbel natural finish moisturizing foundation spf 25', 135, 75570);
insert into inventory (name, quantity, price) values ('galentic vitamin a d', 112, 228458);
insert into inventory (name, quantity, price) values ('amoxicillin', 117, 463840);
insert into inventory (name, quantity, price) values ('hydrocortisone', 137, 308297);
insert into inventory (name, quantity, price) values ('raspberry guava antibacterial', 55, 94776);
insert into inventory (name, quantity, price) values ('coffea cruda', 150, 298341);
insert into inventory (name, quantity, price) values ('cephalexin', 96, 203925);
insert into inventory (name, quantity, price) values ('metoprolol tartrate', 106, 228425);
insert into inventory (name, quantity, price) values ('fluoxetine hydrochloride', 131, 422017);
insert into inventory (name, quantity, price) values ('phenylephrine hydrochloride', 88, 316975);
insert into inventory (name, quantity, price) values ('minocycline hydrochloride', 51, 169881);
insert into inventory (name, quantity, price) values ('nu-derm system normal-dry', 97, 286107);
insert into inventory (name, quantity, price) values ('activive', 87, 265920);
insert into inventory (name, quantity, price) values ('boscia restorative day moisture broad spectrum spf 15 for dry skin', 106, 483748);
insert into inventory (name, quantity, price) values ('esika perfect match', 60, 199465);
insert into inventory (name, quantity, price) values ('fluoxetine', 52, 376849);
insert into inventory (name, quantity, price) values ('comtan', 76, 344328);
insert into inventory (name, quantity, price) values ('degree', 67, 374234);
insert into inventory (name, quantity, price) values ('naphazoline hydrochloride and pheniramine maleate', 136, 443444);
insert into inventory (name, quantity, price) values ('cozaar', 95, 296230);
insert into inventory (name, quantity, price) values ('ery-tab', 66, 112666);
insert into inventory (name, quantity, price) values ('alprazolam', 105, 69991);
insert into inventory (name, quantity, price) values ('tramadol hydrochloride and acetaminophen', 59, 406770);
insert into inventory (name, quantity, price) values ('pink bismuth', 83, 364721);
insert into inventory (name, quantity, price) values ('quetiapine fumarate', 87, 250343);
insert into inventory (name, quantity, price) values ('shiseido sheer matifying compact (refill)', 129, 183626);
insert into inventory (name, quantity, price) values ('diazepam', 131, 281717);
insert into inventory (name, quantity, price) values ('imitrex', 102, 186724);
insert into inventory (name, quantity, price) values ('montelukast sodium', 75, 265690);
insert into inventory (name, quantity, price) values ('purified water', 78, 149055);
insert into inventory (name, quantity, price) values ('bacitracin zinc and polymyxin b sulfate', 112, 371963);
insert into inventory (name, quantity, price) values ('dg health hemorrhoidal', 148, 236864);
insert into inventory (name, quantity, price) values ('ropinirole hydrochloride', 126, 207735);
insert into inventory (name, quantity, price) values ('triple protection broad spectrum sunscreenspf 30', 95, 108476);
insert into inventory (name, quantity, price) values ('piperacillin and tazobactam', 55, 94001);
insert into inventory (name, quantity, price) values ('lorac foundation fair', 111, 170955);
insert into inventory (name, quantity, price) values ('promethazine hydrochloride', 58, 69451);
insert into inventory (name, quantity, price) values ('lorcet 10/650', 111, 258998);
insert into inventory (name, quantity, price) values ('demeclocycline hydrochloride', 69, 475151);
insert into inventory (name, quantity, price) values ('zolpidem tartrate', 99, 98458);
insert into inventory (name, quantity, price) values ('ondansetron', 103, 361579);
insert into inventory (name, quantity, price) values ('metronidazole', 128, 427972);
insert into inventory (name, quantity, price) values ('risperidone', 110, 478782);
insert into inventory (name, quantity, price) values ('contac cold and flu', 50, 94409);
insert into inventory (name, quantity, price) values ('arnica montana (whole plant)', 142, 218574);
insert into inventory (name, quantity, price) values ('organ-i nr', 60, 449018);
insert into inventory (name, quantity, price) values ('treatment set ts341451', 135, 385368);
insert into inventory (name, quantity, price) values ('up and up acid reducer', 104, 493586);
insert into inventory (name, quantity, price) values ('besthealth cough relief sugar free cherry flavor', 58, 332675);
insert into inventory (name, quantity, price) values ('ginsamin memory', 94, 112890);
insert into inventory (name, quantity, price) values ('all day relief', 132, 478401);
insert into inventory (name, quantity, price) values ('infants gas relief', 130, 90296);
insert into inventory (name, quantity, price) values ('couch quack grass', 75, 428485);
insert into inventory (name, quantity, price) values ('donepezil hydrochloride', 144, 166948);
insert into inventory (name, quantity, price) values ('clarithromycin', 134, 445859);
insert into inventory (name, quantity, price) values ('tretinoin', 110, 265968);
insert into inventory (name, quantity, price) values ('ruby-cell 4u mist', 95, 295905);
insert into inventory (name, quantity, price) values ('silicea', 53, 486522);
insert into inventory (name, quantity, price) values ('clindamycin palmitate hydrochloride', 55, 155557);
insert into inventory (name, quantity, price) values ('lyrica', 108, 229687);
insert into inventory (name, quantity, price) values ('western ragweed pollen', 93, 292819);
insert into inventory (name, quantity, price) values ('lbel couleur luxe amplifier xp', 135, 226652);
insert into inventory (name, quantity, price) values ('acnefree clear skin treatments', 103, 290041);
insert into inventory (name, quantity, price) values ('spherusol', 129, 476147);
insert into inventory (name, quantity, price) values ('delsym', 85, 424674);
insert into inventory (name, quantity, price) values ('lorac foundation light', 101, 490944);
insert into inventory (name, quantity, price) values ('equetro', 142, 406346);
insert into inventory (name, quantity, price) values ('multi-symptom cold flu and sore throat', 67, 331327);
insert into inventory (name, quantity, price) values ('pilocarpine hydrochloride', 77, 165628);
insert into inventory (name, quantity, price) values ('lamivudine and zidovudine', 54, 74277);
insert into inventory (name, quantity, price) values ('carvedilol', 101, 234070);
insert into inventory (name, quantity, price) values ('glipizide and metformin hcl', 88, 492775);
insert into inventory (name, quantity, price) values ('mobic', 108, 383777);
insert into inventory (name, quantity, price) values ('pramipexole dihydrochloride', 52, 298892);
insert into inventory (name, quantity, price) values ('ofloxacin', 75, 73285);
insert into inventory (name, quantity, price) values ('idarubicin hydrochloride', 107, 264504);
insert into inventory (name, quantity, price) values ('mamonde brightening pact 10hr n21', 96, 53640);
insert into inventory (name, quantity, price) values ('valtrex', 71, 461722);
insert into inventory (name, quantity, price) values ('banana boat ultra defense sheer protect spf 30', 107, 106252);
insert into inventory (name, quantity, price) values ('bethanechol chloride', 88, 493271);
insert into inventory (name, quantity, price) values ('nighttime sleep aid', 69, 429320);
insert into inventory (name, quantity, price) values ('psoriaflora', 50, 387937);
insert into inventory (name, quantity, price) values ('ibuprofen and pseudoephedrine hydrochloride', 118, 83734);
insert into inventory (name, quantity, price) values ('cold medicine', 61, 389436);
insert into inventory (name, quantity, price) values ('fexofenadine hcl and pseudoephedrine hci', 65, 62841);
insert into inventory (name, quantity, price) values ('diltiazem hydrochloride', 53, 287660);
insert into inventory (name, quantity, price) values ('quality choice maximum strength urinary pain relief', 116, 193582);
insert into inventory (name, quantity, price) values ('readycleanse', 78, 61232);
insert into inventory (name, quantity, price) values ('medium foundation spf 15', 118, 459416);
insert into inventory (name, quantity, price) values ('oxygen', 81, 490852);
insert into inventory (name, quantity, price) values ('risperidone', 88, 294406);
insert into inventory (name, quantity, price) values ('equate dual action complete', 96, 489263);
insert into inventory (name, quantity, price) values ('bloating', 115, 280241);
insert into inventory (name, quantity, price) values ('tazicef', 150, 272754);
insert into inventory (name, quantity, price) values ('aspirin', 149, 290500);
insert into inventory (name, quantity, price) values ('advanced lightning', 57, 292076);
insert into inventory (name, quantity, price) values ('lidocaine hydrochloride', 137, 98686);
insert into inventory (name, quantity, price) values ('vaporizing chest', 125, 420117);
insert into inventory (name, quantity, price) values ('pamidronate disodium', 149, 148626);
insert into inventory (name, quantity, price) values ('losartan potassium and hydrochlorothiazide', 97, 271403);
insert into inventory (name, quantity, price) values ('diltiazem hydrochloride', 150, 201451);
insert into inventory (name, quantity, price) values ('crest 3d white', 60, 288942);
insert into inventory (name, quantity, price) values ('iaso progressive age care', 90, 241531);
insert into inventory (name, quantity, price) values ('vagi-cure (maximum strength)', 65, 205933);
insert into inventory (name, quantity, price) values ('olanzapine', 74, 133385);
insert into inventory (name, quantity, price) values ('mirtazapine', 117, 421291);
insert into inventory (name, quantity, price) values ('hangover relief', 122, 234343);
insert into inventory (name, quantity, price) values ('atenolol', 85, 447466);
insert into inventory (name, quantity, price) values ('leader adult tussin dm', 135, 393720);
insert into inventory (name, quantity, price) values ('ha2cg evolution', 145, 148021);
insert into inventory (name, quantity, price) values ('western waterhemp pollen', 106, 223870);
insert into inventory (name, quantity, price) values ('presidents choice', 93, 292992);
insert into inventory (name, quantity, price) values ('oxygen', 57, 464543);
insert into inventory (name, quantity, price) values ('brovex psb', 68, 310033);
insert into inventory (name, quantity, price) values ('hand and nature sanitizer', 134, 168010);
insert into inventory (name, quantity, price) values ('capecitabine', 103, 89144);
insert into inventory (name, quantity, price) values ('donatussin drops', 71, 494619);
insert into inventory (name, quantity, price) values ('dior bronze collagen activ spf 15 002', 83, 170392);
insert into inventory (name, quantity, price) values ('rheumatic - joint care', 79, 263572);
insert into inventory (name, quantity, price) values ('azithromycin dihydrate', 91, 361967);
insert into inventory (name, quantity, price) values ('umcka coldcare alcohol free cherry', 57, 311365);
insert into inventory (name, quantity, price) values ('laneige mystic veil foundation', 150, 427878);
insert into inventory (name, quantity, price) values ('degree', 74, 53190);
insert into inventory (name, quantity, price) values ('fentanyl', 134, 93760);
insert into inventory (name, quantity, price) values ('blueberry', 63, 420061);
insert into inventory (name, quantity, price) values ('no7 lift and luminate foundation sunscreen broad spectrum spf 15 cool vanilla', 113, 168125);
insert into inventory (name, quantity, price) values ('metronidazole', 69, 272826);
insert into inventory (name, quantity, price) values ('oxygen', 116, 174096);
insert into inventory (name, quantity, price) values ('levothyroxine sodium', 135, 246023);
insert into inventory (name, quantity, price) values ('mirtazapine', 87, 484225);
insert into inventory (name, quantity, price) values ('sensible', 93, 87195);
insert into inventory (name, quantity, price) values ('buspirone hcl', 65, 278493);
insert into inventory (name, quantity, price) values ('equaline nighttime cough relief', 71, 453737);
insert into inventory (name, quantity, price) values ('levetiracetam', 121, 104919);
insert into inventory (name, quantity, price) values ('lucky', 86, 203469);
insert into inventory (name, quantity, price) values ('wheat bunt', 128, 152719);
insert into inventory (name, quantity, price) values ('lisinopril', 140, 53314);
insert into inventory (name, quantity, price) values ('ranitidine', 98, 240109);
insert into inventory (name, quantity, price) values ('mineral', 77, 253041);
insert into inventory (name, quantity, price) values ('12 hour cough relief', 60, 270270);
insert into inventory (name, quantity, price) values ('ventolin', 106, 113093);
insert into inventory (name, quantity, price) values ('lyrica', 142, 229480);
insert into inventory (name, quantity, price) values ('amlodipine besylate and benazepril hydrochloride', 84, 112356);
insert into inventory (name, quantity, price) values ('secret invisible bora bora', 126, 210643);
insert into inventory (name, quantity, price) values ('baraclude', 114, 378523);
insert into inventory (name, quantity, price) values ('childrens mucus relief', 57, 217700);
insert into inventory (name, quantity, price) values ('delflex', 70, 69994);
insert into inventory (name, quantity, price) values ('spf 30 sunscreen tottle', 50, 113324);
insert into inventory (name, quantity, price) values ('superdent', 64, 427531);
insert into inventory (name, quantity, price) values ('g.m. collin acne', 60, 412532);
insert into inventory (name, quantity, price) values ('hydrocodone bitartrate and acetaminophen', 88, 130027);
insert into inventory (name, quantity, price) values ('ramipril', 70, 195144);
insert into inventory (name, quantity, price) values ('black pepper', 114, 446559);
insert into inventory (name, quantity, price) values ('mucus-clear', 92, 337699);
insert into inventory (name, quantity, price) values ('quetiapine fumarate', 93, 236887);
insert into inventory (name, quantity, price) values ('care one ibuprofen', 56, 278862);
insert into inventory (name, quantity, price) values ('ranitidine', 62, 187788);
insert into inventory (name, quantity, price) values ('dg health stomach relief', 86, 168707);
insert into inventory (name, quantity, price) values ('lachesis mutus kit refill', 113, 76260);
insert into inventory (name, quantity, price) values ('arrid extra dry', 74, 212867);
insert into inventory (name, quantity, price) values ('dr. jart bounce beauty balm 02 medium-deep', 69, 296819);
insert into inventory (name, quantity, price) values ('apis mellifica', 85, 191174);
insert into inventory (name, quantity, price) values ('carya illinoinensis pollen', 70, 122575);
insert into inventory (name, quantity, price) values ('l occitane anti-dandruff sensitive scalp', 141, 364151);
insert into inventory (name, quantity, price) values ('sterile diluent for allergenic extract', 72, 365178);
insert into inventory (name, quantity, price) values ('enalapril maleate', 121, 394392);
insert into inventory (name, quantity, price) values ('nighttime sleep aid', 146, 455967);
insert into inventory (name, quantity, price) values ('cetafen extra', 54, 337007);
insert into inventory (name, quantity, price) values ('seroquel', 97, 204456);
insert into inventory (name, quantity, price) values ('equate tussin', 84, 328615);
insert into inventory (name, quantity, price) values ('promethazine hydrochloride', 137, 69714);
insert into inventory (name, quantity, price) values ('oxybutynin chloride', 110, 329577);
insert into inventory (name, quantity, price) values ('mirtazapine', 50, 90198);
insert into inventory (name, quantity, price) values ('up and up childrens mucus relief', 115, 163742);
insert into inventory (name, quantity, price) values ('naproxen', 93, 426582);
insert into inventory (name, quantity, price) values ('vamousse lice treatment', 127, 198812);
insert into inventory (name, quantity, price) values ('theraworx pre-moistened cloths', 101, 475071);
insert into inventory (name, quantity, price) values ('naproxen sodium', 63, 476977);
insert into inventory (name, quantity, price) values ('ciprofloxacin', 125, 182528);
insert into inventory (name, quantity, price) values ('modlina peptide soothing essential hydrogel mask pack', 109, 215551);
insert into inventory (name, quantity, price) values ('lady speed stick', 127, 215006);
insert into inventory (name, quantity, price) values ('careone pain relief', 144, 312144);
insert into inventory (name, quantity, price) values ('bacti-free tm', 97, 466517);
insert into inventory (name, quantity, price) values ('sodium bicarbonate', 102, 114900);
insert into inventory (name, quantity, price) values ('banana boat', 67, 342397);
insert into inventory (name, quantity, price) values ('propoxyphene napsylate and acetaminophen', 105, 179011);
insert into inventory (name, quantity, price) values ('oxygen', 82, 493118);
insert into inventory (name, quantity, price) values ('tetracycline hydrochloride', 137, 225848);
insert into inventory (name, quantity, price) values ('ditropan', 60, 203666);
insert into inventory (name, quantity, price) values ('beech pollen', 98, 91249);
insert into inventory (name, quantity, price) values ('naproxen', 76, 364747);
insert into inventory (name, quantity, price) values ('sulwhasoo lumitouch base', 60, 415638);
insert into inventory (name, quantity, price) values ('prednisone', 88, 345509);
insert into inventory (name, quantity, price) values ('alka-seltzer plus', 146, 133949);
insert into inventory (name, quantity, price) values ('fanapt', 80, 212265);
